replicas: 3
ingress:
  enabled: false
  hostname: "rancher.my-cluster.local"
  tls:
    source: letsEncrypt
  #ingressClassName: "nginx"
  extraAnnotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
