apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gitlab-certificate
  namespace: gitlab
spec:
  secretName: gitlab-tls-secret
  dnsNames:
  - gitlab.my-cluster.local
  issuerRef:
    name: letsencrypt-production     # Ajusta según el nombre de tu ClusterIssuer
    kind: ClusterIssuer
